palette = 'catppuccin_mocha'

add_newline = true

format = """
 $hostname$nix_shell$directory$git_branch$git_state$git_status$helm$python$golang$kubernetes$azure
 $jobs$character"""

# right_format = """$azure$kubernetes"""

[character]
success_symbol = '[ ](bold_green)'
error_symbol = '[ ](bold_red)'
vimcmd_symbol = '[ ](bold_green)'

[fill]
symbol = '-'

[directory]
format = 'in [$path]($style)[$read_only]($read_only_style) '

[hostname]
ssh_only = true
ssh_symbol = ' '
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

[azure]
disabled = false
format = ' [$symbol($subscription)]($style) '
symbol = '  '
style = 'blue bold'

[kubernetes]
disabled = false
format = ' [$symbol($cluster)]($style) '
symbol = '󱃾  '
style = 'green'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[jobs]
symbol = ' '
number_threshold = 4
symbol_threshold = 1

[nix_shell]
disabled = false
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [󱄅 (\($name\))](bold blue) '
